name: das-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy<2.0.0
  - scipy
  - matplotlib
  - pandas
  - pywavelets
  - pyproj
  - scikit-image
  - ipykernel
  - h5py
  - xarray
  - tqdm
  - folium
  - contextily
  - pip
  - pip:
      - arlpy
